### PR TITLE
Build x86_64 Linux wheels in the CI

### PR DESCRIPTION
**Pull request by kopytjuk**
For non-conda installations pre-compiled wheels are very helpful and handy.

Many projects like shapely or numpy ([in the future](https://github.com/pandas-dev/pandas/issues/44027#issuecomment-1076952117)) consider building wheels with github actions and `cibuildwheel`. Thus the ``wheel.yml` is added.

### CODE REVIEW

**Comment by wolfv** [comment]
Hey, awesome! 

I am a bit confused about the mix of places from where dependencies come from. 

Boost is installed once by downloading from jfrog, and once through yum?

**Comment by kopytjuk** [comment]
That is a fair question and I am currently under investigation, but I am trying to elaborate.

CGAL5.4 inclused `function_output_iterator.h` in [multiple ](https://github.com/CGAL/cgal/search?q=function_output_iterator) header files.

This include is only possible since boost/iterator 1.6.6, see [here](https://github.com/boostorg/iterator/tree/boost-1.66.0/include/boost/iterator), in 1.6.5 this header file [does not exist](https://github.com/boostorg/iterator/tree/boost-1.65.0/include/boost/iterator).

Now the problems:
- `sudo apt-get` on ubuntu 18.04 (bionic) only has the [version 1.6.5](https://packages.ubuntu.com/bionic/libboost-dev)
- the Docker image `quay.io/pypa/manylinux2014_x86_64:2022-03-31-361e6b6`, which is used to build the `manylinux` wheels, has an even older version available, namely [1.5.3](https://centos.pkgs.org/7/centos-x86_64/boost-1.53.0-28.el7.x86_64.rpm.html).

I am investigating whether the built `.so` wheel links against the boost library or just compiled the header files provided by boost ...

**Comment by kopytjuk** [comment]
@wolfv here an update

After unpacking `skgeom-0.1.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl`, you will see following structure:

```
├── skgeom
│   ├── __init__.py
│   ├── _skgeom.cpython-38-x86_64-linux-gnu.so
│   ├── _version.py
│   ├── draw.py
│   └── utils.py
├── skgeom-0.1.2.dist-info
│   ├── LICENSE
│   ├── METADATA
│   ├── RECORD
│   ├── WHEEL
│   └── top_level.txt
└── skgeom.libs
    ├── libgmp-afec2dd4.so.10.2.0
    └── libmpfr-54b13606.so.4.1.1
```

Looking at compiled binary with `readelf` you'll see that the linked libraries are attached to the wheel archive:

```shell
ubuntu@ip-172-31-9-217:~/.pyenv/versions/3.8.13/lib/python3.8/site-packages/skgeom$ readelf -d _skgeom.cpython-38-x86_64-linux-gnu.so

Dynamic section at offset 0x1f828000 contains 32 entries:
  Tag        Type                         Name/Value
 0x000000000000000f (RPATH)              Library rpath: [$ORIGIN/../skgeom.libs]
 0x0000000000000001 (NEEDED)             Shared library: [libmpfr-54b13606.so.4.1.1]
 0x0000000000000001 (NEEDED)             Shared library: [libgmp-afec2dd4.so.10.2.0]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
 0x000000000000000c (INIT)               0x56000
 0x000000000000000d (FINI)               0x81f670
 0x0000000000000019 (INIT_ARRAY)         0x9fa8e0
 0x000000000000001b (INIT_ARRAYSZ)       152 (bytes)
```

Now it seems we have complete wheels for distribution.

**Comment by kopytjuk** [comment]
@wolfv is something missing from your side?

**Comment by tmolteno** [comment]
Anyone know why this is not progressing. Hugely important that people can install this package this way.

**Comment by wolfv** [comment]
@tmolteno it's mostly that I didn't have much time, unfortunately. I would be happy to add others as maintainers! :)
A wheel would be awesome.

**Pull request merged**
