### PR TITLE
FIX: CGAL 5.2 build (version parsing & build issue)

### PR DESCRIPTION
**Pull request by neok-m4700**
Hi,
I also hit #57 with latest CGAL version `5.2`.
This PR fixes version parsing.
Thanks.

### CODE REVIEW

**Comment by wolfv** [comment]
Thanks! Any chance you also have a fix for the issue on CI?

**Comment by neok-m4700** [comment]
> Thanks! Any chance you also have a fix for the issue on CI?

Yes, working on:
```bash
$PREFIX/include/CGAL/Straight_skeleton_2/Polygon_offset_builder_2_impl.h:215:21: error: cannot convert ‘CGAL::Point_2<CGAL::Epick>’ to ‘const Point_2&’ {aka ‘const CGAL::Point_2<CGAL::Epeck>&’}
  215 |     aPoly->push_back(*lP);
      |     ~~~~~~~~~~~~~~~~^~~~~
```
Exact (`Epeck`) vs Inexact (`Epick`) Kernel issue ...

**Comment by neok-m4700** [comment]
So the `Travis` build errors out on `MacOS`, because it uses an older `CGAL` release, but `5.2` on `Linux` and `Win` on AppVeyor is OK.

**Comment by wolfv** [comment]
Thanks this is awesome!

**Pull request merged**
