### PR TITLE
[WIP / RFC] SurfaceMesh and corefinement

### PR DESCRIPTION
**Pull request by darikg**
Hi @wolfv, I started this because I'd love pythonic access to CGAL's [corefinement](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__corefinement__grp.html) operators, also just fun a learning experience with pybind11 and C++ in general. Submitting a PR early because 1) not sure if SurfaceMesh is in-scope for skgeom and 2) I don't have much experience with C++ so curious if this approach seems reasonable to you.

Main todos:
  - [ ] Better property support
    - [ ] Vert properties: support all types, not just doubles
    - [x] Support face properties
  - [x] Wrap the `corefine_and_compute_intersection ` methods, etc
    - [ ] And support their various named parameters
  - [ ] Tests

### CODE REVIEW

**Comment by wolfv** [comment]
Hi @darikg sorry for the late reply! Sounds like a great idea, thanks for this initiative!

So far it looks all good to me! It will be interesting to have a draw function for these meshes :)

Any specific questions you have?

**Comment by darikg** [comment]
no need to apologize I'm obviously pretty slow at this!

**Comment by darikg** [comment]
> It will be interesting to have a draw function for these meshes :)

It will be pretty easy to add some conversion methods for [Pyvista](https://www.pyvista.org/) and let that handle all the visualization

**Comment by wolfv** [comment]
Sounds like a plan!

**Comment by darikg** [comment]
Added some really simple tests. This currently supports face and vertex properties as doubles only (I'm not good enough with C++ templates to generalize them to other types.) Right now I have a really simple test on the intersection/union/difference methods -- not sure exactly how to test these properly  without  doing a bunch of geometry to figure out what the result "should" be beyond testing there's no runtime errors.

I'd love to have this available from conda-forge -- how do you feel about merging as-is? Or anything else you'd want as a minimum?

**Comment by darikg** [comment]
still picking away at this :)

latest update:

  - use the proper to/from_polygon_soup api for mesh construction instead of the manual approach I was using before (which could result in invalid meshes if the surface wasn't manifold)
 
  - Vertex / Face / Edge indexes are wrapped as python classes
 
  - Property maps are generic over key/value types, wrapped as standalone python objects, and support pythonic indexing with the Vertex/Face/Edge handle objects, and vectors thereof.
 
    - One downside of this approach, if I understand the pybind11 documentation correctly, is that every combination of key and value type needs to be specified separately, which will require a fair amount of copy-pasting code.
   
  - Support writing to/from PLY and OFF files
   
  - It's not included here, but I was also able to wrap some more methods from the polygon mesh processing module, like mesh smoothing, refining, remeshing, and fairing. Most of these require Eigen, which is easy to support with conda but I'm not sure how you felt about that as an (optional) dependency.
 
Can I ask a broader question? In some of your modules, like the interior skeleton (which happened to be extremely useful for me, so thanks again!) you go to some significant work to safely wrap pointers to vertex handles, etc. Here I'm just returning the handles directly. I think this should be ok because the surface mesh vertex handles etc are just opaque integers so copying is cheap. Do you think this approach is reasonable?

**Comment by darikg** [comment]
Hi @wolfv,

I think I've been asking way too much of your time here. (Sorry for that!) I'm going to close this PR and pull the whole thing into a standalone package [here](https://github.com/darikg/seagullmesh).

cheers!

**Pull request closed without merging**
