### PR TITLE
add simplification for polygons

### PR DESCRIPTION
**Pull request by poke1024**
This adds a `simplify` command and a demo notebook.

I tried to capture all essential CGAL features. What's missing is hybrid cost functions, that are not even used in the CGAL examples themselves.

### CODE REVIEW

**Comment by wolfv** [comment]
Looks awesome!

**Comment by poke1024** [comment]
Added one more case, where you can pass a list of polygons and added a demo for that in the notebook.

Preservation of topology seems to break down at some point (i.e. if the simplify constant gets too aggressive), and I'm not sure why.

**Comment by poke1024** [comment]
Also, I'm not sure about the mode names, `sqeuclidean`, `ratio`, `count`. There might be better ones. Any ideas?

**Comment by wolfv** [comment]
seems like `sqeuclidean` is also used by scipy (https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.spatial.distance.sqeuclidean.html) so I think it's fine with me to keep the names (ratio and count are pretty clear).
Let me know if you want me to investigate the build issue. I published the 0.1.1 version of  scikit-geometry on Windows (conda-forge) yesterday night, by the way.

I am happy to make a new release with these changes (and also to update the docs to include your notebooks).

**Comment by poke1024** [comment]
The build issue seems that in older CGAL versions there is no `holes()` method that returns a container. I'll change that.

Exactly, I chose `sqeuclidean` because I think people might know it from scipy.

**Comment by poke1024** [comment]
Hm, it now fails because the simplifcation API has slightly changed from CGAL 4 (Travis) to CGAL 5 (what I'm building against).

Specifically there's an additional parameter (https://github.com/CGAL/cgal/blob/releases/CGAL-4.14-branch/Polyline_simplification_2/examples/Polyline_simplification_2/simplify_polyline.cpp).

Is this a good time to bump Travis/CI to CGAL 5?

**Comment by wolfv** [comment]
hey, IMO we can totally only use CGAL 5.0. Just need to figure out what's available on conda-forge.

**Comment by wolfv** [comment]
Ok, I think I see what's going on: the `cgal` package stopped receiving any updates, only the `cgal-cpp` package is bumped to 5.0 (because it's header only now). 
But since we're currently installing `cgal`, it holds back `cgal-cpp`. Let me fix that.

**Comment by wolfv** [comment]
I tried to push the fix for travis to your branch, but it doesn't work as you didn't tick the box :) feel free to apply this patch:

```patch
diff --git a/.appveyor.yml b/.appveyor.yml
index 95c8d7f..ea8eed2 100644
--- a/.appveyor.yml
+++ b/.appveyor.yml
@@ -29,8 +29,8 @@ install:
   - conda config --set always_yes yes --set changeps1 no
   - conda update -q conda
   - conda info -a
-  - conda install cgal cgal-cpp pybind11 matplotlib -c conda-forge
+  - conda install cgal-cpp pybind11 matplotlib -c conda-forge
   - python -m pip install -e . -vvv
 
 build_script:
-  - python -c "import skgeom; print(skgeom.Point2(0, 5))"
\ No newline at end of file
+  - python -c "import skgeom; print(skgeom.Point2(0, 5))"
diff --git a/.travis.yml b/.travis.yml
index fe40df6..7463b68 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -33,7 +33,7 @@ install:
         export CXX=clang++ CC=clang;
       fi
     # Install host dependencies
-    - conda install cgal multipledispatch pybind11 matplotlib -c conda-forge
+    - conda install cgal-cpp pybind11 matplotlib -c conda-forge
     # Install build dependencies
     - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
         conda install gxx_linux-64 libgcc -c conda-forge;
```

**Comment by wolfv** [comment]
okay, now just need to remove the linking in `setup.py`! :+1:

**Comment by poke1024** [comment]
Windows now seems to lack mpfr: `LINK : fatal error LNK1181: cannot open input file 'mpfr.lib'`. Strange.

**Pull request merged**
