### PR TITLE
Fix pybind

### PR DESCRIPTION
**Pull request by t-bltg**
Fix https://github.com/scikit-geometry/scikit-geometry/issues/81, tested under `pybind11@2.8.0` (build pass, `python@3.10, gcc@11.2.0`).

Not checked for correctness though.

### CODE REVIEW

**Comment by btel** [comment]
I tested the fix and it works for me (it builds and the tests pass). Why was the MR closed @t-bltg?

**Comment by wolfv** [comment]
Hey @btel great to see you on this repository! You are a person I trust – if you want to help maintain scikit-geometry please let me know! I have had way too little time recently to properly maintain this library :(

**Comment by t-bltg** [comment]
> I tested the fix and it works for me (it builds and the tests pass). Why was the MR closed @t-bltg?

I don't remember ;)

**Comment by btel** [comment]
hey @wolfv, I am definitely the same person ;-) I started using scikit-geometry in one of my projects (unfortunately it can not be shared publicly 🙄). I will definitely help but I am afraid the complexity of the bindings go far beyond my knowledge of c++ ;-) I saw that you merged the fix but appveyor is failling for some (probably independent) reason:

```
C:\condaskgeom\Library\include\boost/core/bit.hpp(529): error C3249: illegal statement or sub-expression for 'constexpr' function
    C:\condaskgeom\Library\include\boost/core/bit.hpp(529): note: see usage of '++'
    C:\condaskgeom\Library\include\boost/core/bit.hpp(513): error C3259: 'constexpr' functions can only have one return statement
    C:\condaskgeom\Library\include\boost/multiprecision/detail/standalone_config.hpp(21): fatal error C1189: #error:  "Boost.Config is considered a requirement to use Boost.Multiprecision in standalone mode. A package is provided at https://github.com/boostorg/multiprecision/releases"
    error: command 'C:\\Program Files (x86)\\Microsoft Visual 
```

https://ci.appveyor.com/project/wolfv/scikit-geometry/builds/48620045#L591

**Pull request merged**
